spring:
  application:
    name: order-service
    config:
      customer-url: http://localhost:8222/api/v1/customers
      product-url: http://localhost:8222/api/v1/products
      payment-url: http://localhost:8222/api/v1/payments
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: ndach
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8070