spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ndach
    password: root
    url: jdbc:postgresql://localhost:5432/payment_db
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: http://localhost:9092
      key-serializer: org.apache.common.serialization.StringSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:org.softgraf.ecommerce.paymentserver.notification.PaymentNotificationRequest
server:
  port: 8060