spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: ndach
    password: root
    driver.class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8050